# configuracao do bd
quarkus.datasource.db-kind = postgresql
quarkus.datasource.username = topicos1
quarkus.datasource.password = 123456
quarkus.datasource.jdbc.url = jdbc:postgresql://localhost:5434/topicos1db

# nomes de tabelas/colunas em snake_case (GuitarraEletrica -> guitarra_eletrica)
quarkus.hibernate-orm.physical-naming-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

%dev.quarkus.hibernate-orm.database.generation=drop-and-create
%test.quarkus.datasource.db-kind=h2
%test.quarkus.datasource.username=sa
%test.quarkus.datasource.password=sa
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:test;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
%test.quarkus.hibernate-orm.database.generation=drop-and-create

# desabilitar o docker 
# quarkus.devservices.enabled=false

quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.log.bind-parameters=true